name: Python Tests

# Trigger the workflow on push or pull request events to any branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Test against multiple Python versions
        python-version: [3.7, 3.8, 3.9, '3.10', 3.11]

    steps:
    # Step to checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step to set up the specified Python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Step to cache dependencies to speed up workflow runs
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step to install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    # Step to lint the code using flake8
    - name: Lint code
      run: |
        pip install flake8
        flake8 .

    # Step to run tests with coverage
    - name: Run tests with coverage
      run: |
        pip install coverage
        coverage run -m pytest
        coverage report
        coverage xml

    # Step to upload coverage results to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.xml